services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
    volumes:
      - ./compose/ipfs-data:/data/ipfs
      - ./swarm.key:/data/ipfs/swarm.key
    networks:
      - ipfs-net
    environment:
      IPFS_CONFIG: '{"Routing": {"Type": "dht"}}'
      IPFS_API_ADDR: /ip4/0.0.0.0/tcp/5001
      IPFS_GATEWAY_ADDR: /ip4/0.0.0.0/tcp/8080

  ipfs-cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: ipfs-cluster
    ports:
      - "9090:9090"
      - "9094:9094"
    environment:
      CLUSTER_PEERNAME: ipfs-cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET} 
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 
      CLUSTER_MONITORPINGINTERVAL: 2s 
    volumes:
      - ./compose/ipfs-cluster-data:/data/ipfs-cluster
    networks:
      - ipfs-net
    depends_on:
      - ipfs
   
networks:
  ipfs-net:
    driver: bridge

