services:
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:release
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    environment:
      LIBP2P_FORCE_PNET: 1 # Prevents the node from starting if it can't stay private (if the key doesn't load)
    volumes:
      - ./data/ipfs/data:/data/ipfs
      - ./data/ipfs/staging:/export

  cluster:
    container_name: cluster
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: main-node
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "9096:9096" # Cluster swarm endpoint, allows communication with peers
      - "127.0.0.1:9094:9094" # Open API port (allows ipfs-cluster-ctl usage on host)
    volumes:
      - ./data/cluster:/data/ipfs-cluster